name: build image and push to registry
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t arswendosryhd/ecommerce-payment-gateway:latest .
      - name: Login to Docker Hub
        run: docker login -u arswendosryhd -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker push arswendosryhd/ecommerce-payment-gateway:latest
